---

- name: " Creating an ec2-instance"
  hosts: localhost
  vars:
    keypair_name: "ansible"      
    access_key: "XXXXXXXXXXXXXXXX"
    secret_key: "YYYYYYYYYYYYYYYYYYYYYYYYYYY"
    region: "ap-south-1"
    sg1: "ansible-remote"
    sg2: "ansible-webserver"

  tasks:

    - name: "Creating key pair"
      ec2_key:
        aws_access_key: "{{ access_key }}"
        aws_secret_key: "{{ secret_key }}"
        region: "{{ region }}"
        name: "{{ keypair_name }}"
        state: present
      register: keypair_content



    - name: "Aws-Saving key pair"
      when: keypair_content.changed == true
      copy:
        content: "{{ keypair_content.key.private_key }}"
        dest: "{{ keypair_name }}.pem"
        mode: 0400


    - name: "Creating Security Group {{ sg1 }}"
      ec2_group:
        aws_access_key: "{{ access_key }}"
        aws_secret_key: "{{ secret_key }}"
        region: "{{ region }}"
        name: "{{ sg1 }}"
        description: "Allows only 22 connection"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip:
              - 0.0.0.0/0
            cidr_ipv6:
              - ::/0

        tags:
          name: "{{ sg1 }}"
      register: sg1_status




    - name: "Creation of Security Group {{ sg2 }}"
      ec2_group:
        aws_access_key: "{{ access_key }}"
        aws_secret_key: "{{ secret_key }}"
        region: "{{ region }}"
        name: "{{ sg2 }}"
        description: "Allows 80 443 connection"
        rules:
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip:
              - 0.0.0.0/0
            cidr_ipv6:
              - ::/0
        rules:
          - proto: tcp
            from_port: 443
            to_port: 443
            cidr_ip:
              - 0.0.0.0/0
            cidr_ipv6:
              - ::/0

        tags:
          name: "{{ sg2 }}"
      register: sg2_status


    - name: "Creation of ec2-Instance"
      ec2:
        aws_access_key: "{{ access_key }}"
        aws_secret_key: "{{ secret_key }}"
        region: "{{ region }}"
        key_name: "{{ keypair_name }}"
        instance_type: "t2.micro"
        image: "ami-052cef05d01020f1d"
        group_id:
          - "{{ sg1_status.group_id }}"
          - "{{ sg2_status.group_id }}"
        instance_tags:
          Name: "webserver"
        count_tag:
          Name: "webserver"
        exact_count: 2
